idf_component_register(SRCS
                          "device/ble_device_controller.cpp"
                          "device/device_role.cpp"
                          "switchbot.cpp"
                          "switchbot_net.cpp"
                          "switchbot_over_web.cpp"
                    INCLUDE_DIRS ".")
