idf_component_register(SRCS
                          "device/ble_device_controller.cpp"
                          "device/device_role.cpp"
                          "switchbot.cpp"
                          "switchbot_net.cpp"
                          "switchbot_over_web.cpp"
                          "lcd/st7789.cpp"
                          "lcd/Vernon_ST7789T/Vernon_ST7789T.cpp"
                          "rtc8010/rtc8010.c"
                    INCLUDE_DIRS
                          "."
                          "lcd/"
                          "lcd/Vernon_ST7789T/"
                        )
